__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$detA=\begin{vmatrix} 1 & -2 \\ 3 & -4 \end{vmatrix} = 2 \neq 0$

$detA_{1}=\begin{vmatrix} 1 & -2 \\ 7 & -4 \end{vmatrix} = 10$

$detA_{2}=\begin{vmatrix} 1 & 1 \\ 3 & 7 \end{vmatrix} = 4$

$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$

$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$

In [1]:
import numpy as np
from scipy import linalg

In [2]:
x = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]])

A = np.round(np.linalg.det(x))

In [4]:
x_1 = x.copy()
x_1[:,0] = b

A_1 = np.round(np.linalg.det(x_1))

In [5]:
x_2 = x.copy()
x_2[:,1] = b

A_2 = np.round(np.linalg.det(x_2))

In [6]:
A_1 / A

5.0

In [7]:
A_2 / A

2.0

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$detA=\begin{vmatrix} 2 & -1 & 5 \\ 1 & 1 & -3 \\ 2 & 4 & 1 \end{vmatrix} = 43 \neq 0$

$detA_{1}=\begin{vmatrix} 10 & -1 & 5 \\ -2 & 1 & -3 \\ 1 & 4 & 1 \end{vmatrix} = 86$

$detA_{2}=\begin{vmatrix} 2 & 10 & 5 \\ 1 & -2 & -3 \\ 2 & 1 & 1 \end{vmatrix} = -43$

$detA_{3}=\begin{vmatrix} 2 & -1 & 10 \\ 1 & 1 & -2 \\ 2 & 4 & 1 \end{vmatrix} = 43$

$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$

$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$

$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$U = \begin{pmatrix} 3 & 26 & 30 \\ 2 & 9 & 12 \\ 1 & 2 & 4 \\ \end{pmatrix}$

$L = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$

$U = \begin{pmatrix} 3 & 26 & 30 \\ 0 & - \frac{25}{3} & -8 \\ 0 & -\frac{20}{3} & -6 \\ \end{pmatrix}$

$U = \begin{pmatrix} 3 & 26 & 30 \\ 0 & -8 \frac{1}{3} & -8 \\ 0 & 0 & \frac{2}{5} \\ \end{pmatrix}$

$L = \begin{pmatrix} 1 & 0 & 0 \\ \frac{2}{3} & 1 & 0 \\ \frac{1}{3} & \frac{4}{5} & 1 \end{pmatrix}$

In [10]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

P, L, U = linalg.lu(A)

print(f'U =\n {U}')
print(f'L =\n {L}')

U =
 [[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]
L =
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$U = \begin{pmatrix} 4 & 22 & 53 & 33 \\ 2 & 5 & 8 & 9 \\ 3 & 18 & 29 & 18 \\ 1 & 1 & 2 & 4 \end{pmatrix}$

$U = \begin{pmatrix} 4 & 22 & 53 & 33 \\ 0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\ 0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} \end{pmatrix}$

$U = \begin{pmatrix} 4 & 22 & 53 & 33 \\ 0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\ 0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} \end{pmatrix}$

$U = \begin{pmatrix} 4 & 22 & 53 & 33 \\ 0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\ 0 & 0 & 2 \frac{5}{8} & 1 \frac{3}{8} \end{pmatrix}$

$U = \begin{pmatrix} 4 & 22 & 53 & 33 \\ 0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\ 0 & 0 & 0 & - \frac{4}{41} \end{pmatrix}$

$L = \begin{pmatrix} 1 & 0 & 0 & 0 \\ \frac{1}{2} & 1 & 0 & 0 \\ \frac{3}{4} & -\frac{1}{4} & 1 & 0 \\ \frac{1}{4} & \frac{3}{4} & - \frac{7}{41} & 1 \end{pmatrix}$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$U = \begin{pmatrix} 11 & 7 & 5 \\ 9 & 8 & 4 \\ 2 & 1 & 3 \end{pmatrix}$

$U = \begin{pmatrix} 11 & 7 & 5 \\ 0 & \frac{25}{11} & - \frac{1}{11} \\ 0 & - \frac{3}{11} & \frac{23}{11} \end{pmatrix}$

$U = \begin{pmatrix} 11 & 7 & 5 \\ 0 & \frac{25}{11} & - \frac{1}{11} \\ 0 & 0 & \frac{52}{25} \end{pmatrix}$

$L = \begin{pmatrix} 1 & 0 & 0 \\ \frac{9}{11} & 1 & 0 \\ \frac{2}{11} & - \frac{3}{25} & 1 \end{pmatrix} $

$\begin{cases} y_{1} = -6, \\ \frac{9}{11} y_{1} + y_{2} =-5, \\ \frac{2}{11}y_{1} - \frac{3}{25} y_{2} + y_{3} = 1. \end{cases}$

$y_{1} = -6$ $y_{2} = -\frac{1}{11}$ $y_{3} = \frac{52}{25}$

$Ux=y:$

$\begin{cases} 11x_{1} + 7x_{2} + 5x_{3} = -6, \\ \frac{25}{11} x_{2} - \frac{1}{11} x_{3}= - \frac{1}{11}, \\ \frac{52}{25} x_{3} = \frac{52}{25} \end{cases}$

$x_{1} = -1$
$x_{2} = 0$
$x_{3} = 1$

$2 \cdot (-1) + 0 + 3 \cdot 1 = 1$
$11 \cdot (-1) + 7 \cdot 0 + 5 \cdot 1 = -6$
$9 \cdot (-1) + 8 \cdot 0 + 4 \cdot 1 = -5$

In [11]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

P, L, U = linalg.lu(A)

print(f'U =\n {U}')
print(f'L =\n {L}')

U =
 [[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]
L =
 [[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]


In [12]:
lu, piv = linalg.lu_factor(A)
x = linalg.lu_solve((lu, piv), b)

print(f' x_1 = {x[0]}\n x_2 = {x[1]}\n x_3 = {x[2]}')

 x_1 = -1.0000000000000002
 x_2 = 2.4424906541753446e-16
 x_3 = 1.0


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$\begin{pmatrix} 81 & -45 & 45 \\ -45 & 50 & -15 \\ 45 & -15 & 38 \end{pmatrix}$

$l_{11} =\sqrt{a_{11}} = \sqrt{81} = 9$
$l_{21} =\frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5$
$l_{31} =\frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$

$l_{22} = \sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - (-5)^2} = 5$
$l_{32} = \frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}(-15 - (-5) \cdot 5) = 2$

$l_{33} = \sqrt{a_{33}-l_{32}^{2}-l_{31}^{2}} = \sqrt{38 - 2^2 - 5^2} = 3$

$L = \begin{pmatrix} 9 & 0 & 0 \\ -5 & 5 & 0 \\ 5 & 2 & 3 \end{pmatrix}, \; \; L^{T} = \begin{pmatrix} 9 & -5 & 5 \\ 0 & 5 & 2\\ 0 & 0 & 3 \end{pmatrix}.$

$Ly=b:$

$\begin{cases} 9 y_1 = 531 \\ -5 y_1 + 5 y_2 = -460 \\ 5 y_1 + 2 y_2 + 3 y_3 = 193 \end{cases}$

$y_1 = 59$
$y_2 = -33$
$y_3 = -12$

$L^{T}x=y:$

$\begin{cases} 9 x_1 - 5 x_2 + 5 x_3 = 59 \\ 5 x_2 + 2 x_3 = -33 \\ 3 x_3 = -12 \end{cases}$

$x_1 = 6$
$x_2 = -5$
$x_3 = -4$

$\begin{cases} 81 \cdot 6 - 45 \cdot (-5) + 45 \cdot (-4) = 531 \\ -45 \cdot 6 + 50 \cdot (-5) - 15 \cdot (-4) = -460 \\ 45 \cdot 6 - 15 \cdot (-5) + 38 \cdot (-4) = 193 \end{cases}$

In [13]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
L = np.linalg.cholesky(A)
print(f'L=\n{L} \n L.T=\n{L.T}')

L=
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]] 
 L.T=
[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]
